### ISSUE TITLE
Use not only in overleaf?

### ISSUE THREAD

**Issue by XiangLiu-github** [alcantara-pereira/shortleaf#1]
Hi, thanks for this, it is very helpful and convenient, I am wondering if it is possible to include other websites, not only overleaf? Maybe it is better to have a blank for users to add other webs?

**Comment by alcantara-pereira** [comment]
Hi @XiangLiu-github,
First of all, thank you! 
Unfortunately, to register the keybinds the extension uses the Ace* API. Thus, it would only work on other services that use this same editor. 
Given that, and for simplicity, I would prefer keeping the scope of this project restricted to Overleaf. But if you do have a specific suggestion of such a service, do let me know and I will check how easy it would be to adapt it.

*: Ace editor is a JavaScript library that Overleaf uses. It implements the actual text/code editor part of it.

**Comment by XiangLiu-github** [comment]
Thanks for the explanation! My university has a service that is totally identical to overleaf (possibly use the Ace API), https://tex.nju.edu.cn/project, but in another web and only for institutional login.
Is it that impossible to test that? or how do I know if it is Ace editor?
Anyway, thanks for your work!

**Comment by alcantara-pereira** [comment]
OK, you can adapt it and test it by doing the following:

- Clone or download the repository to a location of your choosing (note that if you delete it, you will delete the extension).
- Edit the 'manifest.json' file: change the overleaf url to the one you linked.
- Follow the instruction in Step 2 of [this](https://support.google.com/chrome/a/answer/2714278?hl=en) page on how to install and test an extension from source.

That should really be all. Please do let me know if it works!

**Comment by alcantara-pereira** [comment]
Oh, and I don't know how chrome handles two extensions with the same name entry, so it might be wise to also change the name field too in the 'manifest.json' file if you're keeping the published version installed. Just to make sure that doesn't cause any problems...

**Comment by XiangLiu-github** [comment]
Thanks! It worked for me! I will just use it then.
